version: '3.8'

services:
  db:
    container_name: db_for_ciaa
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin_for_ciaa
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db  
  app:
    container_name: app_ciaa
    build: .
    command: bash -c "sleep 15 && uvicorn fwp_app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000
    depends_on:
      - db
      - pgadmin
    volumes:
      - .:/app


  redis:
    container_name: redis_for_ciaa
    image: redis:latest
    ports:
      - 6379:6379
    restart: always

  celery_worker:
    container_name: celery_worker2
    build: .
    volumes:
      - .:/app
    command: bash -c "ls && celery -A fwp_app.celery_worker worker --loglevel=info"
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_URL=${CELERY_RESULT_BACKEND} 
    depends_on:
      - app
      - redis
    
  # flower:
  #   container_name: flower
  #   build: .
  #   command: celery -A celery_scheduler.celery_worker flower --port=5555
  #   ports:
  #     - 5556:5555
  #   environment:
  #     - CELERY_BROKER_URL=${CELERY_BROKER_URL}
  #     - CELERY_RESULT_URL=${CELERY_RESULT_BACKEND}
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - app
  #     - redis
  #     - celery_worker

  